---
- name: Playbook to Update cache, upgrade packages and reboot os if necessary
  hosts: all
  tasks:
    - name: Create new container snapshot
      community.general.proxmox_snap:
   #     api_user: root@pam
     #   api_password: 
        api_host: 192.168.23.38
        vmid: 212
        state: present
        snapname: pre-updates
